cats/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]
urlpatterns += staticfiles_urlpatterns()

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('cats/', views.cats_index, name='index'),
    path('cats/<int:cat_id>/', views.cats_details, name='details'),
    path('cats/create/', views.CreateCat.as_view(), name='create_cat'),
    path('cats/<int:pk>/update/', views.UpdateCat.as_view(), name='cats_update'),
    path('cats/<int:pk>/delete/', views.DeleteCat.as_view(), name='cats_delete'),
    path('cats/<int:cat_id>/add_appointment/', views.add_appointment, name='add_appointment'),
    path('cats/<int:cat_id>/delete_appointment/<int:appointment_id>', views.delete_appointment, name='delete_appointment'),
    path('cats/<int:cat_id>/assoc_date/<int:date_id>/', views.assoc_date, name='assoc_date'),
    path('play/', views.PlayList.as_view(), name='play_index'),
    path('play/<int:pk>/', views.PlayDetail.as_view(), name='play_detail'),
    path('play/create/', views.PlayCreate.as_view(), name='play_create'),
    path('play/<int:pk>/update/', views.PlayUpdate.as_view(), name='play_update'),
    path('play/<int:pk>/delete/', views.PlayDelete.as_view(), name='play_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Play_Date(models.Model):
    name = models.TextField(max_length=50)
    image = models.TextField()
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('play_detail', kwargs={'pk': self.id})

class Cat(models.Model):
    name = models.TextField(max_length=100)
    breed = models.TextField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    image = models.TextField()
    temperment = models.TextField()
    play = models.ManyToManyField(Play_Date)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('details', kwargs={'cat_id': self.id})


VISITS = (
    ('V', 'Vaccine'),
    ('C', 'Checkup'),
    ('G', 'Grooming'),
)

class Appointment(models.Model):
    date = models.DateField('Visit Date')
    visit = models.TextField(choices=VISITS, default=VISITS[0][0])

    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']
        
    def __str__(self):
        return f'{self.get_visit_display()} on {self.date}'

main_app/forms.py
from django.forms import ModelForm
from .models import Appointment

class AppointmentForm(ModelForm):
    class Meta:
        model = Appointment
        fields =['date', 'visit']

main_app/views.py
from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from django.http import HttpResponse

from .models import Cat, Play_Date, Appointment

from .forms import AppointmentForm

# Create your views here.

class CreateCat(CreateView):
    model = Cat
    fields = ['name', 'breed', 'description', 'age', 'image', 'temperment']
    success_url = '/cats/'

class UpdateCat(UpdateView):
    model = Cat
    fields = ['breed', 'description', 'age', 'temperment']

class DeleteCat(DeleteView):
    model = Cat
    success_url = '/cats/'

def cats_index(request):
    cats = Cat.objects.all()
    return render(request, 'cats/index.html', {'cats': cats})



def home(request):
    return render(request, 'home.html')
 

def cats_details(request, cat_id):
    cats = Cat.objects.get(id=cat_id)
    no_play_date = Play_Date.objects.exclude(id__in = cats.play.all().values_list('id'))
    appointment_form = AppointmentForm()
    return render(request, 'cats/details.html', {'cats': cats, 'appointment_form': appointment_form, 'play': no_play_date})

def add_appointment(request, cat_id):
    form = AppointmentForm(request.POST)
    if form.is_valid():
        new_appointment = form.save(commit=False)
        new_appointment.cat_id = cat_id
        new_appointment.save()
    return redirect('details', cat_id=cat_id)

def delete_appointment(request, cat_id, appointment_id):
    Appointment.objects.filter(id=appointment_id).delete()
    return redirect('details', cat_id=cat_id)

def assoc_date(request, cat_id, date_id):
    Cat.objects.get(id=cat_id).play.add(date_id)
    return redirect('details', cat_id=cat_id)

class PlayList(ListView):
    model = Play_Date


class PlayDetail(DetailView):
    model = Play_Date


class PlayCreate(CreateView):
    model = Play_Date
    fields = '__all__'


class PlayUpdate(UpdateView):
    model = Play_Date
    fields = ['name', 'image']


class PlayDelete(DeleteView):
    model = Play_Date
    success_url = '/play/'

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Cat Girl</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper deep-purple accent-2">
        <a class="brand-logo left" href="/">
          <img id="brand-logo" src="https://i.imgur.com/Ryz76fa.jpg" width="58">
        </a>
        <ul class="right">
            <li><a href="{% url 'create_cat' %}">Add A Cat</a></li>
            <li><a href="{% url 'play_create' %}">Add A Play Date</a></li>
					<li><a href="{% url 'play_index' %}">View All Play Dates</a></li>
            <li><a href="/cats">View My Babies</a></li>
            
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer panel deep-purple accent-2">
    <div class="right">All Rights Reserved, &copy; 2023 Cat Girl &nbsp;</div>
  </footer>
</body>
</html>
<div align="center" style="z-index:9;visibility:visible;"><a href="https://www.totallyfreecursors.com/" target="_blank" class="tfc"></a></div><style>HTML,BODY{cursor: url("https://downloads.totallyfreecursors.com/cursor_files/cat11.ani"), url("https://downloads.totallyfreecursors.com/thumbnails/cat12.gif"), auto;}</style>

main_app/templates/cats/details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foster Cats</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
          <div class="nav-wrapper deep-purple accent-2">
            <a class="brand-logo left"><img id="brand-logo" src="https://i.imgur.com/Ryz76fa.jpg" width="58"></a>
            <ul class="right">
                <li><a href="/">Home</a></li>
                <li><a href="/cats">View My Babies</a></li>
            </ul>
          </div>
        </nav>
      </header>
      <div class="container">
        <div class="row pic">
          <div class="col s6">
            <div class="card cat-image-card" style="margin-bottom: 20px;">
              <div class="card-content center">
                <h1>{{ cats.name }}</h1>
                <div class="row">
                  <div class="col s12">
                    <img class="responsive-img" src="{{cats.image}}">
                  </div>
                </div>
                <p>"{{cats.temperment}}"</p>
                <div class="card-action">
                  <a href="{% url 'cats_update' cats.id %}">Edit</a>
                  <a href="{% url 'cats_delete' cats.id %}">Delete</a>
                </div>
              </div>
            </div>
          </div>
          <div class="col s6">
            <div class="card appointment-card">
              <h2>Appointments</h2>
              <div class="card-content">
                <form action="{% url 'add_appointment' cats.id %}" method="POST">
                  {% csrf_token %}
                  {{ appointment_form.as_p }}
                  <button class="btn-floating btn-large pulse-light pink" type="submit"><i class="material-icons">♡</i></button>
                </form>
                <table class="striped responsive-table" style="font-size: 0.9em;">
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Visit</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for appointment in cats.appointment_set.all %}
                    <tr>
                      <td>{{appointment.date}}</td>
                      <td>{{appointment.get_visit_display}}</td>
                      <td><a href=" {% url 'delete_appointment' cats.id appointment.id %} ">Delete</a></td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="col s6">
            <h3>{{ cats.name }}'s Play Date</h3>
            {% if cats.play.count %}
            {% for date in cats.play.all %}
            
            {% if cats.name == date.name %}
            {% else %}
            <div class="card">
              <div class="card-content">
                <span class="card-title">
                  <h4>{{ date.name }}</h4>
                </span>
                <img class="responsive-img" src='{{ date.image }}' alt="url"> 
              </div>
            </div>
            {% endif %}
            
            {% endfor %}
            {% else %}
            <h5>No Play Date :(</h5>
            {% endif %}
          </div>
          <div class="col s6">
            <h3>Available Play Dates</h3>
            {% if play.count %}
            {% for date in play.all %}
            {% if cats.name == date.name %}
            {% else %}
            <div class="card">
              <div class="card-content">
                <span class="card-title">
                  {{ date.name }}
                </span>
              </div>
              <div class="card-action">
                <form action="{% url 'assoc_date' cats.id date.id %}" method="post">
                  {% csrf_token %}
                  <button class="btn-floating btn-large pulse-light pink" type="submit"><i class="material-icons">♡</i></button>
                </form>
              </div>
            </div>
            {% endif %}
            {% endfor %}
            {% else %}
            <h5>{{cats.name}} Already Has All Available Play Dates</h5>
            {% endif %}
  </div>
  </div>
  <script>
    const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  
  const selectEl = document.getElementById('id_visit');
  M.FormSelect.init(selectEl);
</script>
</div>
<footer class="page-footer deep-purple accent-2">
    <div class="right">All Rights Reserved, &copy; 2023 Cat Girl &nbsp;</div>
  </footer>
  </body>
  </html>
<div align="center" style="z-index:9;visibility:visible;"><a href="https://www.totallyfreecursors.com/" target="_blank" class="tfc"></a></div><style>HTML,BODY{cursor: url("https://downloads.totallyfreecursors.com/cursor_files/cat11.ani"), url("https://downloads.totallyfreecursors.com/thumbnails/cat12.gif"), auto;}</style>

main_app/templates/cats/index.html
{% extends 'base.html' %}
{% block content %}

<h1>List of Foster Cats</h1>

{% for cat in cats %}
  <div class="card card-panel deep-purple accent-4 card-panel hoverable">
    <div class="card-content deep-purple accent-1">
      <span class="card-title">{{ cat.name }}</span>
      <p>Breed: {{ cat.breed }}</p>
      <p>Description: {{ cat.description }}</p>
      {% if cat.age > 2 %}
        <p>Age: {{ cat.age }}</p>
      {% else %}
        <p>Age: Kitten</p>
      {% endif %}
      <a href="/cats/{{cat.id}}" class="btn-floating pulse-light pink"><i class="material-icons">♡</i></a>
    </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

    <h1>About Cat Girl</h1>
<hr />
<p class="about">This site is dedicated to showing off my fosters. You can help me foster a cat by donating cat food and supplies. All donations goes towards the future of fosters until adopted into their forever home.</p>

<img src="https://static01.nyt.com/images/2022/11/29/science/00tb-cats1/00tb-cats1-mediumSquareAt3X.jpg " width="500" height="600" class="catpic">




{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Cat</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'details' cat.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Cat</h1>
  {% endif %}

  <form action="" method="post">
   
    {% csrf_token %}
    <table>
    
      {{ form.as_table }}
    </table>
    <button class="btn-floating pulse-light pink" type="submit"><i class="material-icons">♡</i></button>
   
  </form>
{% endblock %}

main_app/templates/main_app/play_date_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Play Date</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'play_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/play_date_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Date Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ play_date.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'play_update' play_date.id%}">Edit</a>
        <a href="{% url 'play_delete' play_date.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/play_date_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Play Date</h1>
{% endif %}

<form action="" method="post">

	{% csrf_token %}
	<table>

		{{ form.as_table }}
	</table>
	<button class="btn-floating pulse-light pink" type="submit"><i class="material-icons">♡</i></button>
</form>
{% endblock %}

main_app/templates/main_app/play_date_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Play Date List</h1>

{% for date in play_date_list %}
  <a href="{% url 'play_detail' date.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ date.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}